[workspace]
resolver = "2"
members = [
    "src/os",
    "src/kernel",
    "src/hal",
    "src/hal-x86_64",
    "src/hal-arm64",
    "src/pi5-image",
    "src/exec",
    "src/shell",
    "src/xtask",
]

[workspace.package]
edition = "2021"
license = "MIT"
publish = false

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
